@startuml
skinparam backgroundColor #FFFFFF

skinparam sequence {
	ArrowColor DeepSkyBlue
	ActorBorderColor DeepSkyBlue
	LifeLineBorderColor blue
	LifeLineBackgroundColor #A9DCDF

	ParticipantBorderColor DeepSkyBlue
	ParticipantBackgroundColor DodgerBlue
	ParticipantFontName Impact
	ParticipantFontSize 17
	ParticipantFontColor #FFFFFF

	ActorBackgroundColor aqua
	ActorFontColor DeepSkyBlue
	ActorFontSize 17
	ActorFontName Aapex
}
Client -> Server: Product query(date, coordinates, accessibility)
Server --> Client: Product portfolio

Client -> Server: AvailabilityRequest(travel and passenger information)
Server --> Client: AvailabilityResponse(softbooked reservations)

Client -> Server: ReservationRequest(reservetions, customer information)
Server --> Client: ReservationResponse(ticket payloads)
@enduml